concept:
  class: "http://www.w3.org/2004/02/skos/core#Concept"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  thumbnail: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  researchAreaOf:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    title: "http://vivoweb.org/ontology/core#hrJobTitle"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
  broaderConcept:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  narrowerConcept:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  relatedConcept:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  sameAs:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  modTime: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime"