organization:
  class: "http://xmlns.com/foaf/0.1/Organization"

  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"

  identifier: "http://vivo.library.tamu.edu/ontology/TAMU#OrgID"

  name: "http://www.w3.org/2000/01/rdf-schema#label"

  abbreviation: "http://vivoweb.org/ontology/core#abbreviation"
  overview: "http://vivoweb.org/ontology/core#overview"

  address:
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    region: "http://www.w3.org/2006/vcard/ns#region"
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    country: "http://www.w3.org/2006/vcard/ns#country"

  email: "http://www.w3.org/2006/vcard/ns#email"
  geo: "http://www.w3.org/2006/vcard/ns#geo"

  links:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"

  researchAreas: "http://www.w3.org/2000/01/rdf-schema#label"

  grants: "http://www.w3.org/2000/01/rdf-schema#label"

  successor: "http://www.w3.org/2000/01/rdf-schema#label"
  predecessor: "http://www.w3.org/2000/01/rdf-schema#label"

  degrees:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    field: "http://vivoweb.org/ontology/core#majorField"
    date: "http://vivoweb.org/ontology/core#dateTime"

  faculty:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    title: "http://vivoweb.org/ontology/core#hrJobTitle"

  partOf: "http://www.w3.org/2000/01/rdf-schema#label"
  hasParts: "http://www.w3.org/2000/01/rdf-schema#label"
