document:
  class: "http://purl.org/ontology/bibo/Document"
  title: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  thumbnail: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  abstract: "http://purl.org/ontology/bibo/abstract"
  abbreviation: "http://vivoweb.org/ontology/core#abbreviation"
  publicationVenue: "http://www.w3.org/2000/01/rdf-schema#label"
  publicationVenueFor: "http://www.w3.org/2000/01/rdf-schema#label"
  etdChairedBy:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    email: "http://www.w3.org/2006/vcard/ns#email"
  author:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    rank: "http://vivoweb.org/ontology/core#rank"
  authorList: "http://vivo.library.tamu.edu/ontology/TAMU#fullAuthorList"
  editor:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    rank: "http://vivoweb.org/ontology/core#rank"
  editorList: "http://vivo.library.tamu.edu/ontology/TAMU#fullEditorList"
  bookTitle: "http://vivo.library.tamu.edu/ontology/TAMU#bookTitleForChapter"
  translator:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  status: "http://www.w3.org/2000/01/rdf-schema#label"
  publicationDate: "http://vivoweb.org/ontology/core#dateTime"
  publisher:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  dateFiled: "http://vivoweb.org/ontology/core#dateTime"
  dateIssued: "http://vivoweb.org/ontology/core#dateTime"
  subjectArea: "http://www.w3.org/2000/01/rdf-schema#label"
  restriction: "http://purl.obolibrary.org/obo/ERO_0000045"
  documentPart:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  chapter: "http://purl.org/ontology/bibo/chapter"
  feature:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  edition: "http://purl.org/ontology/bibo/edition"
  geographicFocus:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  documentationForProjectOrResource:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  outputOfProcessOrEvent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  presentedAt:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  keyword: "http://vivoweb.org/ontology/core#freetextKeyword"
  eanucc13: "http://purl.org/ontology/bibo/eanucc13"
  nihmsid: "http://vivoweb.org/ontology/core#nihmsid"
  pmcid: "http://vivoweb.org/ontology/core#pmcid"
  identifier: "http://purl.org/ontology/bibo/identifier"
  patentNumber: "http://vivoweb.org/ontology/core#patentNumber"
  sameAs:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  doi: "http://purl.org/ontology/bibo/doi"
  oclcnum: "http://purl.org/ontology/bibo/oclcnum"
  isbn10: "http://purl.org/ontology/bibo/isbn10"
  isbn13: "http://purl.org/ontology/bibo/isbn13"
  pmid: "http://purl.org/ontology/bibo/pmid"
  lccn: "http://purl.org/ontology/bibo/lccn"
  issn: "http://purl.org/ontology/bibo/issn"
  eissn: "http://purl.org/ontology/bibo/eissn"
  uri: "http://purl.org/ontology/bibo/uri"
  citedBy:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  citation:
    text: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  citesAsDataSource:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  translation:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  translationOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  globalCitationFrequency: "http://www.w3.org/2000/01/rdf-schema#label"
  iclCode: "http://vivoweb.org/ontology/core#iclCode"
  numberOfPages: "http://purl.org/ontology/bibo/numPages"
  pageStart: "http://purl.org/ontology/bibo/pageStart"
  pageEnd: "http://purl.org/ontology/bibo/pageEnd"
  volume: "http://purl.org/ontology/bibo/volume"
  issue: "http://purl.org/ontology/bibo/issue"
  placeOfPublication: "http://vivoweb.org/ontology/core#placeOfPublication"
  assignee:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  reproducedIn: "http://www.w3.org/2000/01/rdf-schema#label"
  reproduces:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  isAbout:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  specifiedOutputOf:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  isTemplate: "http://purl.obolibrary.org/obo/ARG_0000001"
  mention:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  participatesIn: "http://www.w3.org/2000/01/rdf-schema#label"
  supportedBy:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  modTime: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime"
  receipt: "http://www.w3.org/2000/01/rdf-schema#label"
