person:
  class: "http://xmlns.com/foaf/0.1/Person"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  thumbnail: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  primaryEmail: "http://www.w3.org/2006/vcard/ns#email"
  additionalEmail: "http://www.w3.org/2006/vcard/ns#email"
  phone: "http://www.w3.org/2006/vcard/ns#telephone"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  orcidId: "http://vivoweb.org/ontology/core#orcidId"
  preferredTitle: "http://www.w3.org/2006/vcard/ns#title"
  position:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
  overview: "http://vivoweb.org/ontology/core#overview"
  researchArea: "http://www.w3.org/2000/01/rdf-schema#label"
  geographicFocus:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  hrJobTitle: "http://vivoweb.org/ontology/core#hrJobTitle"
  keyword: "http://vivoweb.org/ontology/core#freetextKeyword"
  headOf:
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  memberOf:
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  hasCollaborator: "http://www.w3.org/2000/01/rdf-schema#label"
  clinicalActivity:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  attendedEvent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  educationAndTraining:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  credentials:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    dateIssued: "http://vivoweb.org/ontology/core#dateTime"
  credentialEligibilityAttained:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  awardAndHonor:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  adviseeOf:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    candidacy: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  selectedPublication:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    venue: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  collectionOrSeriesEditorFor:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  editorOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    publisher: "http://www.w3.org/2000/01/rdf-schema#label"
    fullAuthorList: "http://vivo.library.tamu.edu/ontology/TAMU#fullAuthorList"
    pageStart: "http://purl.org/ontology/bibo/pageStart"
    pageEnd: "http://purl.org/ontology/bibo/pageEnd"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  presentation:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    event: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  featuredIn:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  assigneeForPatent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  translatorOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  researchOverview: "http://vivoweb.org/ontology/core#researchOverview"
  principalInvestigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  coPrincipalInvestigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  investigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  otherResearchActivity:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  teachingOverview: "http://vivoweb.org/ontology/core#teachingOverview"
  teachingActivity:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
  advisee:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    candidacy:  "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  outreachOverview: "http://vivoweb.org/ontology/core#outreachOverview"
  reviewerOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  contactOrProvidorForService:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  organizerOfEvent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  professionalServiceActivity:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  outreachAndCommunityServiceActivity:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    role: "http://www.w3.org/2000/01/rdf-schema#label"
    startDate: "http://vivoweb.org/ontology/core#dateTime"
    endDate: "http://vivoweb.org/ontology/core#dateTime"
  performsTechnique:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  hasExpertiseInTechnique:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  isni: "http://vivo.library.tamu.edu/ontology/TAMU#ISNI"
  netid: "http://vivo.library.tamu.edu/ontology/TAMU#NETID"
  researcherId: "http://vivo.library.tamu.edu/ontology/TAMU#ResearcherId"
  twitter: "http://vivo.library.tamu.edu/ontology/TAMU#twitterId"
  uid: "http://vivo.library.tamu.edu/ontology/TAMU#UID"
  uin: "http://vivo.library.tamu.edu/ontology/TAMU#UIN"
  youtube: "http://vivo.library.tamu.edu/ontology/TAMU#youtube"
  sameAs:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  eraCommonsId: "http://vivoweb.org/ontology/core#eRACommonsId"
  isiResearcherId: "http://vivoweb.org/ontology/core#researcherId"
  scopusId: "http://vivoweb.org/ontology/core#scopusId"
  healthCareProviderId: "http://purl.obolibrary.org/obo/ARG_0000197"
  email: "http://www.w3.org/2006/vcard/ns#email"
  firstName: "http://www.w3.org/2006/vcard/ns#givenName"
  middleName: "http://www.w3.org/2006/vcard/ns#middleName"
  lastName: "http://www.w3.org/2006/vcard/ns#familyName"
  address:
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    region: "http://www.w3.org/2006/vcard/ns#region"
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    country: "http://www.w3.org/2006/vcard/ns#country"
  geographicLocation: "http://www.w3.org/2000/01/rdf-schema#label"
  locatedInFacility: "http://www.w3.org/2000/01/rdf-schema#label"
  fax: "http://www.w3.org/2006/vcard/ns#fax"
  etdChairOf: "http://www.w3.org/2000/01/rdf-schema#label"
  modTime: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime"
