person:
  class: "http://xmlns.com/foaf/0.1/Person"

  uid: "http://vivo.library.tamu.edu/ontology/TAMU#UID"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  firstName: "http://www.w3.org/2006/vcard/ns#givenName"
  middleName: "http://vivoweb.org/ontology/core#middleName"
  lastName: "http://www.w3.org/2006/vcard/ns#familyName"
  overview: "http://vivoweb.org/ontology/core#overview"
  title: "http://vivoweb.org/ontology/core#hrJobTitle"
  email: "http://www.w3.org/2006/vcard/ns#email"
  researcherId: "http://vivoweb.org/ontology/core#researcherId"
  scopusId: "http://vivoweb.org/ontology/core#scopusId"
  orcidId: "http://vivoweb.org/ontology/core#orcidId"

  phone: "http://www.w3.org/2006/vcard/ns#telephone"

  links:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"

  address:
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    region: "http://www.w3.org/2006/vcard/ns#region"
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    country: "http://www.w3.org/2006/vcard/ns#country"

  image:
    filename: "http://vitro.mannlib.cornell.edu/ns/vitro/public#filename"
    mimeType: "http://vitro.mannlib.cornell.edu/ns/vitro/public#mimeType"
    downloadLocation: "http://vitro.mannlib.cornell.edu/ns/vitro/public#downloadLocation"

  thumbnail:
    filename: "http://vitro.mannlib.cornell.edu/ns/vitro/public#filename"
    mimeType: "http://vitro.mannlib.cornell.edu/ns/vitro/public#mimeType"
    downloadLocation: "http://vitro.mannlib.cornell.edu/ns/vitro/public#downloadLocation"


  researchAreas: "http://www.w3.org/2000/01/rdf-schema#label"

  positions: "http://www.w3.org/2000/01/rdf-schema#label"

  organizations: "http://www.w3.org/2000/01/rdf-schema#label"

  courses: "http://www.w3.org/2000/01/rdf-schema#label"

  degrees:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    field: "http://vivoweb.org/ontology/core#majorField"
    date: "http://vivoweb.org/ontology/core#dateTime"

  publications:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
    type:
      value: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
      schema: "http://purl.org/ontology/bibo/"

  grants:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"

  awards:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"

  memberships:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"

  advisings:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"

  workByStudents: "http://www.w3.org/2000/01/rdf-schema#label"
