organization:
  class: "http://xmlns.com/foaf/0.1/Organization"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#downloadLocation"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  overview: "http://vivoweb.org/ontology/core#overview"
  offersDegree:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    field: "http://vivoweb.org/ontology/core#majorField"
  abbreviation: "http://vivoweb.org/ontology/core#abbreviation"
  date: "http://vivoweb.org/ontology/core#dateTime"
  sponsorsAwardOrHonor: "http://www.w3.org/2000/01/rdf-schema#label"
  awardOrHonorGiven: "http://www.w3.org/2000/01/rdf-schema#label"
  awardOrHonorReceived: "http://www.w3.org/2000/01/rdf-schema#label"
  keyword: "http://vivoweb.org/ontology/core#freetextKeyword"
  organizationForTraining: "http://vivoweb.org/ontology/core#majorField"
  people:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    title: "http://vivoweb.org/ontology/core#hrJobTitle"
  hasSubOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  organizationWithin: "http://www.w3.org/2000/01/rdf-schema#label"
  leadOrganizationOf: "http://www.w3.org/2000/01/rdf-schema#label"
  hasCollaboratingOrganizationOrGroup: "http://www.w3.org/2000/01/rdf-schema#label"
  hasAffiliatedOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  memberOf: "http://www.w3.org/2000/01/rdf-schema#label"
  clinicalActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  convenerOfEvent: "http://www.w3.org/2000/01/rdf-schema#label"
  attendedEvent: "http://www.w3.org/2000/01/rdf-schema#label"
  selectedPublication:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  publisherOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  presentation: "http://www.w3.org/2000/01/rdf-schema#label"
  featuredIn:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  assigneeForPatent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  translatorOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  awardsGrant: "http://www.w3.org/2000/01/rdf-schema#label"
  administersGrant: "http://www.w3.org/2000/01/rdf-schema#label"
  subcontractsGrant: "http://www.w3.org/2000/01/rdf-schema#label"
  performsHumanStudy: "http://www.w3.org/2000/01/rdf-schema#label"
  contractOrProviderForService: "http://www.w3.org/2000/01/rdf-schema#label"
  outreachAndCommunityServiceActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  hasEquipment: "http://www.w3.org/2000/01/rdf-schema#label"
  offersCourse: "http://www.w3.org/2000/01/rdf-schema#label"
  orgId: "http://vivo.library.tamu.edu/ontology/TAMU#OrgID"
  phone: "http://www.w3.org/2006/vcard/ns#telephone"
  fax: "http://www.w3.org/2006/vcard/ns#fax"
  emailAddress: "http://www.w3.org/2006/vcard/ns#email"
  address:
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    region: "http://www.w3.org/2006/vcard/ns#region"
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    country: "http://www.w3.org/2006/vcard/ns#country"
  geographicLocation: "http://www.w3.org/2000/01/rdf-schema#label"
  locatedAtFacility: "http://www.w3.org/2000/01/rdf-schema#label"
  predecessorOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  successorOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  governingAuthorityFor: "http://www.w3.org/2000/01/rdf-schema#label"
  hasResearchArea: "http://www.w3.org/2000/01/rdf-schema#label"
