relationship:
  class: "http://vivoweb.org/ontology/core#Relationship"
  title: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  thumbnail: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  abstract: "http://purl.org/ontology/bibo/abstract"
  description: "http://vivoweb.org/ontology/core#description"
  receiptOf:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  awardOrHonorFor:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  awardConferredBy:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  dateTimeInterval:
    start: "http://vivoweb.org/ontology/core#dateTime"
    end: "http://vivoweb.org/ontology/core#dateTime"
  subjectArea:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  awardedBy:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  grantSubcontractedThrough:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  administeredBy:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  geographicFocus:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  subGrant:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  subGrantOf:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  providesFundingFor:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  totalAwardAmount: "http://vivoweb.org/ontology/core#totalAwardAmount"
  directCosts: "http://vivoweb.org/ontology/core#directCosts"
  sponsorAwardId: "http://vivoweb.org/ontology/core#sponsorAwardId"
  localAwardId: "http://vivoweb.org/ontology/core#localAwardId"
  contributor:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  supportedPublicationOrOtherWork:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  yearAwarded: "http://vivoweb.org/ontology/core#dateTime"
  sameAs:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  assignedBy:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  inheresIn:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  isSpecifiedOutputOf:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  outputOf:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  participatesIn:
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    name: "http://www.w3.org/2000/01/rdf-schema#label"
  modTime: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime"